### ISSUE TITLE
CommandLiners.CommandLineUtils HelpOption is defaulting to true when not present

### ISSUE THREAD

**Issue by beardybok** [riezebosch/CommandLiners#5]
I've been banging my head against a wall all day trying to get CommandLineUtils working with your library. Initially thought it was a bug with CommandLineUtils, but I don't think it is.

I've tried using the `app.HelpOption()` method to add the default help, but the bound options object is always setting my `Help` property to `true`, even if I'm not passing any help arguments. I've checked all my configuration sources, but `help:0` and `help` are always present, and provided by the `CommandLineOptionsSource`.

I've just cloned the repo and done some debugging, and I'm pretty sure it comes down to the `Option` class defaulting all `Value`s to `true`:

![image](https://github.com/riezebosch/CommandLiners/assets/165008463/9d9d3efd-a638-4f35-a6ba-c55129d15499)

I've changed it to `false.ToString()` as per the above image, and it seems to be working now.

Wanted to check a few things before I put the effort into a PR;

1) Is this project still active?
2) Will this affect anything else? I'm fairly sure that you wouldn't want boolean options without values to be set to true by default in any circumstance?

Let me know and I'll create the PR and update the tests.

**Comment by beardybok** [comment]
Note that I also tried this with a custom help option (i.e. I removed the `app.HelpOption()` line and created a custom mapping - the result was the same.

**Comment by riezebosch** [comment]
1. it's not that actively used but I'm more than happy to accept improvements and publish a package
2. you're probably right, but it's been a while since I created that

~on top, everything is 💯 TDD with 💯 code coverage so when no tests break I would bite the bullet~, oh tests do break.

**Update 1**

I think the default is `true` so that when you do specify a flag it interprets that as true, not the absence of the parameter

<img width="501" alt="Screenshot 2024-04-10 at 20 30 25" src="https://github.com/riezebosch/CommandLiners/assets/1427334/3a63528b-b3e7-49e6-a647-fbb630330792">

This test shows the absence of the flag/option results already in `False` for the argument.

I must admit I know too little about the `HelpOption`.

**Update 2**

I've written this test:

```csharp
       [Fact]
        public void Help()
        {
            var map = new MapOptions<Simple>();

            var app = new CommandLineApplication();
            using var stream = new MemoryStream();
            using (var writer = new StreamWriter(stream, leaveOpen: true))
            {
                app.Out = writer;
                app.HelpOption();
                app.Option("-d", "debug", CommandOptionType.SingleOrNoValue);
                var result = app.Parse();
                var builder = new ConfigurationBuilder()
                    .AddCommandLineOptions(map.FromCommand(result.SelectedCommand))
                    .Build();

                var options = new Simple();
                builder.Bind(options);

                app.OnExecute(() => 1);
                app.Execute("-h").Should().NotBe(1);
            }

            stream.Seek(0, SeekOrigin.Begin);
            new StreamReader(stream).ReadToEnd().Should().Match("*Show help information*-d*debug*");
        }
```

and it shows that the help does work. I'm assuming you map the help explicitly to a property and I think you shouldn't.

**Update 3**

After some digging I think you've hit a bug: the `CommandOptionType.NoValue` is indeed always bound to true (for some reason).

**Comment by riezebosch** [comment]
I think it should be fixed by now: https://www.nuget.org/packages/CommandLiners/1.0.45 via this commit: https://github.com/riezebosch/CommandLiners/commit/f78e6b3939c04181895a8e4e2732637ff3a868a4

Let me know if that works for you, will close the issue for now.

**Comment by beardybok** [comment]
I am most definitely mapping this to a property, but I feel that is required in order to stop execution if the help option is set? My console app is non-trivial, it incorporates multi-level configuration, end-to-end DI and bootstrap logging.

I'll try the new version out when I get on to this again - apologies, I wrote this and was off work for a few days sick, so now I'm playing catch-up ;)

**Comment by riezebosch** [comment]
for me it works with this recent fix, also when mapping the help option to a property 🤞🏻

**Comment by beardybok** [comment]
Managed to get on to it - seems to be working OK now, thank you @riezebosch :)
